/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    organizations: Organization;
    members: Member;
    subscriptions: Subscription;
    'email-logs': EmailLog;
    events: Event;
    'image-templates': ImageTemplate;
    invitations: Invitation;
    participants: Participant;
    'participant-types': ParticipantType;
    partners: Partner;
    'partner-tiers': PartnerTier;
    'partner-types': PartnerType;
    'email-templates': EmailTemplate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'image-templates': ImageTemplatesSelect<false> | ImageTemplatesSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    'participant-types': ParticipantTypesSelect<false> | ParticipantTypesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'partner-tiers': PartnerTiersSelect<false> | PartnerTiersSelect<true>;
    'partner-types': PartnerTypesSelect<false> | PartnerTypesSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User profile image
   */
  profileImage?: (number | null) | Media;
  roles?: ('super-admin' | 'admin' | 'user')[] | null;
  /**
   * Free: 1 tenant. Pro: 3 tenants. Organizations: 20 tenants.
   */
  pricingPlan?: ('free' | 'pro' | 'organizations' | 'unlimited') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug?: string | null;
  /**
   * The primary owner of this organization (cannot be changed)
   */
  owner: number | User;
  /**
   * Configure custom Resend settings for this organization
   */
  emailConfig?: {
    /**
     * Enable custom email configuration for this organization
     */
    isActive?: boolean | null;
    /**
     * Custom Resend API key (starts with re_). Leave empty to use default.
     */
    resendApiKey?: string | null;
    /**
     * From name for emails sent by this organization
     */
    senderName?: string | null;
    /**
     * From email address for this organization
     */
    fromEmail?: string | null;
    /**
     * Reply-to email address
     */
    replyToEmail?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manages user memberships in organizations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * The user who is a member of the organization
   */
  user: number | User;
  /**
   * The organization this membership belongs to
   */
  organization: number | Organization;
  /**
   * The role this user has in the organization
   */
  role: 'owner' | 'admin' | 'editor' | 'viewer';
  /**
   * The status of this membership
   */
  status: 'active' | 'inactive' | 'removed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manages organization subscriptions and billing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * The organization this subscription belongs to
   */
  organization: number | Organization;
  /**
   * Subscription tier
   */
  tier: 'system-unlimited' | 'free' | 'starter' | 'professional' | 'enterprise';
  /**
   * Billing cycle for the subscription
   */
  billingCycle: 'none' | 'monthly' | 'yearly';
  /**
   * True if organization owner is a super-admin/admin. Grants unlimited access without Stripe.
   */
  isSystemAdmin?: boolean | null;
  /**
   * Number of seats included in the base plan. Use -1 for unlimited.
   */
  seatsIncluded: number;
  /**
   * Additional seats purchased beyond the base plan
   */
  additionalSeats?: number | null;
  /**
   * Price per additional seat in cents (e.g., 500 = €5.00)
   */
  pricePerAdditionalSeat?: number | null;
  /**
   * Stripe Customer ID (e.g., cus_xxxxx)
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe Subscription ID (e.g., sub_xxxxx)
   */
  stripeSubscriptionId?: string | null;
  /**
   * Stripe Price ID for the base plan (e.g., price_xxxxx)
   */
  stripePriceId?: string | null;
  /**
   * Subscription status synced from Stripe
   */
  stripeStatus:
    | 'incomplete'
    | 'incomplete_expired'
    | 'trialing'
    | 'active'
    | 'past_due'
    | 'canceled'
    | 'unpaid'
    | 'paused';
  /**
   * Start of the current billing period
   */
  currentPeriodStart?: string | null;
  /**
   * End of the current billing period
   */
  currentPeriodEnd?: string | null;
  /**
   * Start of trial period
   */
  trialStart?: string | null;
  /**
   * End of trial period (14 days from org creation)
   */
  trialEnd?: string | null;
  /**
   * If true, subscription will be canceled at the end of the current period
   */
  cancelAtPeriodEnd?: boolean | null;
  /**
   * When the subscription was canceled
   */
  canceledAt?: string | null;
  /**
   * When the subscription ended
   */
  endedAt?: string | null;
  /**
   * Default payment method ID in Stripe (e.g., pm_xxxxx)
   */
  stripePaymentMethodId?: string | null;
  /**
   * Last 4 digits of payment card (for display)
   */
  lastFourDigits?: string | null;
  /**
   * Additional metadata (synced with Stripe metadata)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of all sent emails
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  /**
   * The organization this email belongs to
   */
  organization: number | Organization;
  /**
   * The template used for this email (may be deleted)
   */
  template?: (number | null) | EmailTemplate;
  /**
   * Name of the template at time of sending
   */
  templateName: string;
  /**
   * Subject line from the template at time of sending
   */
  templateSubject: string;
  /**
   * Email address of the recipient
   */
  recipientEmail: string;
  /**
   * What triggered this email
   */
  triggerEvent:
    | 'manual'
    | 'scheduled'
    | 'participant.created'
    | 'participant.updated'
    | 'partner.invited'
    | 'event.published'
    | 'form.submitted'
    | 'custom'
    | 'test';
  /**
   * Variables used in the email (JSON format)
   */
  variables?: string | null;
  /**
   * Status of the email
   */
  status: 'sent' | 'failed' | 'scheduled';
  /**
   * Error message if sending failed
   */
  errorMessage?: string | null;
  /**
   * When the email was sent
   */
  sentAt: string;
  /**
   * User who manually sent this email (if applicable)
   */
  sentBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage email templates with dynamic variables
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * Template identifier (e.g., "participant-welcome", "partner-invitation")
   */
  name: string;
  /**
   * What this template is used for
   */
  description?: string | null;
  /**
   * The organization this template belongs to
   */
  organization: number | Organization;
  slug?: string | null;
  /**
   * Whether this template is active and can be used
   */
  isActive?: boolean | null;
  /**
   * Email subject line. Use {{variable}} for dynamic content.
   */
  subject: string;
  /**
   * HTML email body. Use {{variable}} for dynamic content (Handlebars syntax).
   */
  htmlBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Configure when this template should be automatically sent
   */
  automationTriggers?: {
    /**
     * Select the event that triggers this email template
     */
    triggerEvent?:
      | (
          | 'none'
          | 'participant.created'
          | 'participant.updated'
          | 'partner.invited'
          | 'event.published'
          | 'form.submitted'
          | 'custom'
        )
      | null;
    /**
     * Only trigger for specific statuses (leave empty for all statuses)
     */
    statusFilter?: ('not-approved' | 'approved' | 'need-info' | 'cancelled')[] | null;
    /**
     * If "Custom Trigger" is selected, specify the trigger name
     */
    customTriggerName?: string | null;
    /**
     * Delay in minutes before sending (0 for immediate)
     */
    delayMinutes?: number | null;
    /**
     * Optional JSON conditions for when to send (e.g., {"fieldName": "value"})
     */
    conditions?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The organization this event belongs to
   */
  organization: number | Organization;
  name: string;
  slug?: string | null;
  createdBy?: (number | null) | User;
  status?: ('planning' | 'open' | 'closed' | 'archived') | null;
  startDate: string;
  endDate?: string | null;
  timezone?: string | null;
  description?: string | null;
  /**
   * Image for the event.
   */
  image?: (number | null) | Media;
  eventType?: ('physical' | 'online') | null;
  address?: string | null;
  /**
   * Why this event is happening - its purpose and significance
   */
  why?: string | null;
  /**
   * What the event is about - main topics, activities, agenda
   */
  what?: string | null;
  /**
   * Where context - venue name, city, or online platform
   */
  where?: string | null;
  /**
   * Who should attend - target audience, ideal participants
   */
  who?: string | null;
  /**
   * Event theme or tagline
   */
  theme?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Saved canvas templates from the image generator for bulk image creation
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-templates".
 */
export interface ImageTemplate {
  id: number;
  /**
   * Template name (e.g., "Business Card - Blue Theme")
   */
  name: string;
  /**
   * The organization this template belongs to
   */
  organization?: (number | null) | Organization;
  /**
   * Who this template is designed for
   */
  usageType: 'participant' | 'partner' | 'both';
  /**
   * Whether this template is active and can be used
   */
  isActive?: boolean | null;
  /**
   * Canvas width in pixels
   */
  width: number;
  /**
   * Canvas height in pixels
   */
  height: number;
  /**
   * Background image for the template
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Background color (hex code) if no background image is set
   */
  backgroundColor?: string | null;
  /**
   * Canvas elements array with coordinates, text properties, and image URLs. Saved from image-generator tool.
   */
  elements:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Preview thumbnail of the template
   */
  previewImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  /**
   * Email address of the person being invited
   */
  email: string;
  /**
   * The organization this user is being invited to
   */
  organization: number | Organization;
  /**
   * The role this user will have in the organization (admin can manage, editor has edit access, viewer has read-only access)
   */
  role: 'admin' | 'editor' | 'viewer';
  /**
   * Current status of the invitation
   */
  status: 'pending' | 'accepted' | 'declined' | 'expired';
  token: string;
  /**
   * When this invitation expires
   */
  expiresAt: string;
  /**
   * User who sent the invitation
   */
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  /**
   * The organization this participant belongs to (auto-populated from event)
   */
  organization?: (number | null) | Organization;
  name: string;
  email: string;
  event: number | Event;
  participantType: number | ParticipantType;
  status?: ('not-approved' | 'approved' | 'need-info' | 'cancelled') | null;
  /**
   * Profile photo or headshot
   */
  imageUrl?: (number | null) | Media;
  biography?: string | null;
  country?: string | null;
  phoneNumber?: string | null;
  /**
   * Company logo
   */
  companyLogoUrl?: (number | null) | Media;
  companyName?: string | null;
  /**
   * Job title or position
   */
  companyPosition?: string | null;
  companyWebsite?: string | null;
  socialLinks?:
    | {
        platform?: ('linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube' | 'other') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes (not visible to participant)
   */
  internalNotes?: string | null;
  presentationTopic?: string | null;
  presentationSummary?: string | null;
  technicalRequirements?: string | null;
  owner?: (number | null) | User;
  registrationDate?: string | null;
  /**
   * AI-generated LinkedIn post (150-300 characters, professional tone)
   */
  socialPostLinkedIn?: string | null;
  /**
   * AI-generated Twitter/X post (max 280 characters, punchy and concise)
   */
  socialPostTwitter?: string | null;
  /**
   * AI-generated Facebook post (~250 characters, community-focused)
   */
  socialPostFacebook?: string | null;
  /**
   * AI-generated Instagram post (125-150 characters, visual storytelling with emojis)
   */
  socialPostInstagram?: string | null;
  /**
   * When the social posts were last generated
   */
  socialPostGeneratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-types".
 */
export interface ParticipantType {
  id: number;
  /**
   * The organization this participant type belongs to
   */
  organization: number | Organization;
  name: string;
  description?: string | null;
  /**
   * Optional: Link this participant type to a specific event. If set, the public form will be for this event only.
   */
  event?: (number | null) | Event;
  isActive?: boolean | null;
  /**
   * Select which fields are required in the public registration form
   */
  requiredFields?:
    | (
        | 'imageUrl'
        | 'biography'
        | 'country'
        | 'phoneNumber'
        | 'companyLogoUrl'
        | 'companyName'
        | 'companyPosition'
        | 'companyWebsite'
        | 'socialLinks'
        | 'presentationTopic'
        | 'presentationSummary'
        | 'technicalRequirements'
      )[]
    | null;
  /**
   * Enable optional fields selection. When enabled, you can mark displayed fields as optional.
   */
  showOptionalFields?: boolean | null;
  /**
   * Select which fields are optional (shown but not required). Required fields are excluded automatically.
   */
  optionalFields?:
    | (
        | 'imageUrl'
        | 'biography'
        | 'country'
        | 'phoneNumber'
        | 'companyLogoUrl'
        | 'companyName'
        | 'companyPosition'
        | 'companyWebsite'
        | 'socialLinks'
        | 'presentationTopic'
        | 'presentationSummary'
        | 'technicalRequirements'
      )[]
    | null;
  /**
   * Share this link with people to register as this participant type
   */
  publicFormLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * The organization this partner belongs to (auto-populated from event)
   */
  organization?: (number | null) | Organization;
  companyName: string;
  event: number | Event;
  partnerType: number | PartnerType;
  contactPerson: string;
  contactEmail: string;
  /**
   * General company email (different from contact person email)
   */
  email?: string | null;
  /**
   * Partner's primary field or area of expertise
   */
  fieldOfExpertise?: string | null;
  /**
   * Company website URL
   */
  companyWebsiteUrl?: string | null;
  /**
   * Upload company logo image
   */
  companyLogo?: (number | null) | Media;
  /**
   * Direct URL to company logo (alternative to upload)
   */
  companyLogoUrl?: string | null;
  /**
   * Company banner or cover image
   */
  companyBanner?: (number | null) | Media;
  /**
   * Description of the company and its services
   */
  companyDescription?: string | null;
  /**
   * Social media links for the company
   */
  socialLinks?:
    | {
        platform?: ('linkedin' | 'facebook' | 'instagram' | 'other') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  sponsorshipLevel?: string | null;
  additionalNotes?: string | null;
  tier?: (number | null) | PartnerTier;
  status?: ('default' | 'contacted' | 'confirmed' | 'declined') | null;
  owner?: (number | null) | User;
  createdDate?: string | null;
  registrationDate?: string | null;
  /**
   * AI-generated LinkedIn post (150-300 characters, professional tone)
   */
  socialPostLinkedIn?: string | null;
  /**
   * AI-generated Twitter/X post (max 280 characters, punchy and concise)
   */
  socialPostTwitter?: string | null;
  /**
   * AI-generated Facebook post (~250 characters, community-focused)
   */
  socialPostFacebook?: string | null;
  /**
   * AI-generated Instagram post (125-150 characters, visual storytelling with emojis)
   */
  socialPostInstagram?: string | null;
  /**
   * When the social posts were last generated
   */
  socialPostGeneratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-types".
 */
export interface PartnerType {
  id: number;
  /**
   * The organization this partner type belongs to
   */
  organization: number | Organization;
  name: string;
  description?: string | null;
  /**
   * Optional: Link this partner type to a specific event. If set, the public form will be for this event only.
   */
  event?: (number | null) | Event;
  isActive?: boolean | null;
  /**
   * Select which fields are required in the public registration form
   */
  requiredFields?:
    | (
        | 'companyLogo'
        | 'companyLogoUrl'
        | 'companyBanner'
        | 'companyDescription'
        | 'companyWebsiteUrl'
        | 'fieldOfExpertise'
        | 'email'
        | 'socialLinks'
        | 'sponsorshipLevel'
        | 'additionalNotes'
      )[]
    | null;
  /**
   * Enable optional fields selection. When enabled, you can mark displayed fields as optional.
   */
  showOptionalFields?: boolean | null;
  /**
   * Select which fields are optional (shown but not required). Required fields are excluded automatically.
   */
  optionalFields?:
    | (
        | 'companyLogo'
        | 'companyLogoUrl'
        | 'companyBanner'
        | 'companyDescription'
        | 'companyWebsiteUrl'
        | 'fieldOfExpertise'
        | 'email'
        | 'socialLinks'
        | 'sponsorshipLevel'
        | 'additionalNotes'
      )[]
    | null;
  /**
   * Share this link with companies to register as this partner type
   */
  publicFormLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-tiers".
 */
export interface PartnerTier {
  id: number;
  /**
   * The organization this partner tier belongs to
   */
  organization: number | Organization;
  name: string;
  level?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'image-templates';
        value: number | ImageTemplate;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'participant-types';
        value: number | ParticipantType;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'partner-tiers';
        value: number | PartnerTier;
      } | null)
    | ({
        relationTo: 'partner-types';
        value: number | PartnerType;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profileImage?: T;
  roles?: T;
  pricingPlan?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  owner?: T;
  emailConfig?:
    | T
    | {
        isActive?: T;
        resendApiKey?: T;
        senderName?: T;
        fromEmail?: T;
        replyToEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  user?: T;
  organization?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  organization?: T;
  tier?: T;
  billingCycle?: T;
  isSystemAdmin?: T;
  seatsIncluded?: T;
  additionalSeats?: T;
  pricePerAdditionalSeat?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  stripeStatus?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialStart?: T;
  trialEnd?: T;
  cancelAtPeriodEnd?: T;
  canceledAt?: T;
  endedAt?: T;
  stripePaymentMethodId?: T;
  lastFourDigits?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  organization?: T;
  template?: T;
  templateName?: T;
  templateSubject?: T;
  recipientEmail?: T;
  triggerEvent?: T;
  variables?: T;
  status?: T;
  errorMessage?: T;
  sentAt?: T;
  sentBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  slug?: T;
  createdBy?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  timezone?: T;
  description?: T;
  image?: T;
  eventType?: T;
  address?: T;
  why?: T;
  what?: T;
  where?: T;
  who?: T;
  theme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-templates_select".
 */
export interface ImageTemplatesSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  usageType?: T;
  isActive?: T;
  width?: T;
  height?: T;
  backgroundImage?: T;
  backgroundColor?: T;
  elements?: T;
  previewImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  organization?: T;
  role?: T;
  status?: T;
  token?: T;
  expiresAt?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  email?: T;
  event?: T;
  participantType?: T;
  status?: T;
  imageUrl?: T;
  biography?: T;
  country?: T;
  phoneNumber?: T;
  companyLogoUrl?: T;
  companyName?: T;
  companyPosition?: T;
  companyWebsite?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  internalNotes?: T;
  presentationTopic?: T;
  presentationSummary?: T;
  technicalRequirements?: T;
  owner?: T;
  registrationDate?: T;
  socialPostLinkedIn?: T;
  socialPostTwitter?: T;
  socialPostFacebook?: T;
  socialPostInstagram?: T;
  socialPostGeneratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-types_select".
 */
export interface ParticipantTypesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  description?: T;
  event?: T;
  isActive?: T;
  requiredFields?: T;
  showOptionalFields?: T;
  optionalFields?: T;
  publicFormLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  organization?: T;
  companyName?: T;
  event?: T;
  partnerType?: T;
  contactPerson?: T;
  contactEmail?: T;
  email?: T;
  fieldOfExpertise?: T;
  companyWebsiteUrl?: T;
  companyLogo?: T;
  companyLogoUrl?: T;
  companyBanner?: T;
  companyDescription?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  sponsorshipLevel?: T;
  additionalNotes?: T;
  tier?: T;
  status?: T;
  owner?: T;
  createdDate?: T;
  registrationDate?: T;
  socialPostLinkedIn?: T;
  socialPostTwitter?: T;
  socialPostFacebook?: T;
  socialPostInstagram?: T;
  socialPostGeneratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-tiers_select".
 */
export interface PartnerTiersSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  level?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-types_select".
 */
export interface PartnerTypesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  description?: T;
  event?: T;
  isActive?: T;
  requiredFields?: T;
  showOptionalFields?: T;
  optionalFields?: T;
  publicFormLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  organization?: T;
  slug?: T;
  isActive?: T;
  subject?: T;
  htmlBody?: T;
  automationTriggers?:
    | T
    | {
        triggerEvent?: T;
        statusFilter?: T;
        customTriggerName?: T;
        delayMinutes?: T;
        conditions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}